/* 
  MIGRACION PARA AÑADIR VEHÍCULOS A FORMULARIOS
  Esta migración añade los nuevos campos requeridos en el módulo de facturación para
  registrar el vehículo.
*/

ALTER TABLE public.formularios_facturacion 
ADD COLUMN IF NOT EXISTS mod_vehiculo text,
ADD COLUMN IF NOT EXISTS marca text,
ADD COLUMN IF NOT EXISTS descripcion_modelo text;

-- Asegúrate de que existe también una tabla de catálogo de vehículos para
-- que el buscador funcione correctamente. Si no existe, puedes crearla así:

/*
CREATE TABLE IF NOT EXISTS public.vehiculos (
    id bigint generated by default as identity primary key,
    mod_vehiculo text not null unique,
    marca text,
    descripcion_modelo text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
*/
